My home work 1
AnnSchiretz/tech-me-skill-course pull request #1
Opened 2019-10-12 15:53 UTC by AnnSchiretz

2019-10-12 16:17 UTC, AksPokl requested changes
Молодец) и метод написала, и массивы) Но мне кажется, ты невнимательно прочитала задания. Почитай еще раз и переделай)

2019-10-12 16:17 UTC, AksPokl commented on Integer.java
> +public class Integer {
Integer - класс-оболочка для int. И так как такой класс уже существует, ты не можешь свой так назвать.

2019-10-12 16:17 UTC, AksPokl commented on Integer.java
> +public class Integer {
И по-названию, мне непонятно какой так ты делала.

2019-10-12 16:17 UTC, AksPokl commented on LargerNumber.java
> +        if (x > u) {
Я говорила на занятии, что переменные надо называть с умом. Надо практиковаться!

2019-10-12 16:17 UTC, AksPokl commented on LargerNumber.java
> +            System.out.println("This number" + " " + x + " " + "more bigger");
Необязательно использовать " " 
"This number " - лучше так

2019-10-12 16:17 UTC, AksPokl commented on PositiveNumber.java
> +public class PositiveNumber {
Я думаю, ты неправильно поняла задание. Ты тут просто проверяешь - позитивное ли число и печатаешь его.

2019-10-12 16:17 UTC, AksPokl commented on AdditionalTask.java
> +        String[] endingWord = { "программист", "программиста", "программистов" };
Молодец, что решила использовать массив
Только убери лишние пробелы

2019-10-12 16:17 UTC, AksPokl commented on AdditionalTask.java
> +        System.out.println("Применился" + " " + options + " " + "кейс");
"Применился " + options
И так для всех случаев

2019-10-12 16:17 UTC, AksPokl commented on Integer.java
> +        }
Лучше System.out.println(number); поместить после if/else

2019-10-12 16:17 UTC, AksPokl commented on PositiveOrNegativeNumber.java
> +        int positive = 0;
лучше positiveNumber
Никто не называет переменную, используя прилагательное

2019-10-12 16:17 UTC, AksPokl commented on PositiveOrNegativeNumber.java
> +        int positive = 0;
название массива с маленькой буквы

2019-10-12 16:17 UTC, AksPokl commented on PositiveOrNegativeNumber.java
> +        int positive = 0;
Ты точно поняла задачу? Это задача номер 5? если да - переделай)

2019-10-12 16:17 UTC, AksPokl commented on Triangle.java
> +            System.out.println("It`s triangel!");
Если не знаешь, как пишется слово на англ - гугли )

2019-10-12 16:17 UTC, AksPokl commented on NumberOfDigitsInVariable.java
> +public class NumberOfDigitsInVariable {
Название подразумевает - число цифр в переменной) а разве ты тут это делаешь) Подскажи номер задания)

2019-10-12 16:37 UTC, AnnSchiretz commented on AdditionalTask.java
> +        System.out.println("Применился" + " " + options + " " + "кейс");
то есть options = 1, для него будет то, что выше
и так же повторить для options, который будет равен 2 и 3?

2019-10-12 16:38 UTC, AnnSchiretz commented on Integer.java
> +public class Integer {
3) Дано целое число. Если оно является положительным, то прибавить к нему 1. Если отрицательным, то вычесть из него 2. Если нулевым, то заменить его на 10. Вывести полученное число.

вот это я задание делала)

2019-10-12 16:39 UTC, AksPokl commented on AdditionalTask.java
> +        System.out.println("Применился" + " " + options + " " + "кейс");
Я про System.out.println)
Вместо:
 System.out.println("Применился" + " " + options + " " + "кейс")
Надо:
 System.out.println("Применился "  + options  + " кейс")

2019-10-12 16:50 UTC, AnnSchiretz commented on NumberOfDigitsInVariable.java
> +public class NumberOfDigitsInVariable {
1)В переменную записываем число. Надо вывести на экран сколько в этом числе цифр и положительное оно или отрицательное. Например, "это однозначное положительное число". Достаточно будет определить, является ли число однозначным, "двухзначным или трехзначным и более.

вот это я выполняла)
возможно я его не так поняла)

2019-10-12 16:55 UTC, AnnSchiretz commented on PositiveOrNegativeNumber.java
> +        int positive = 0;
да, это 5ая задача
значит я ее не так поняла)
у меня же в конце показывается количество отрицательных и положительных чисел
  System.out.println(positive);
  System.out.println(negative);
я могу просто убрать, например System.out.println
может это сбило как-то

2019-10-12 16:58 UTC, AnnSchiretz commented on PositiveNumber.java
> +public class PositiveNumber {
я могу так же переделать, как и в 5ом задании у меня (ниже)
показать, что вот только положительных чисел

2019-10-12 17:00 UTC, AksPokl commented on Integer.java
> +public class Integer {
То есть происходит определенная логика в классе,  и уже исходя из этой логики ты даешь название - PositiveNegativeApp, PositiveNegativeTaksk и т.д

2019-10-12 17:01 UTC, AksPokl commented on Integer.java
> +public class Integer {
То есть в этом задании. ты должна:
- изменить имя класса 
- переименовать переменные
- переписать System.out.println без  "  "

2019-10-12 17:02 UTC, AnnSchiretz commented on AdditionalTask.java
> +        String[] endingWord = { "программист", "программиста", "программистов" };
лишние пробелы в перечислении элементов массива?
или в скобках после System.out.println?

2019-10-12 17:13 UTC, AksPokl requested changes

2019-10-12 17:13 UTC, AksPokl commented on PositiveOrNegativeNumber.java
> +        int positive = 0;
Оставляй, только положительное число начинается от нуля,  поэтому >=0

2019-10-12 17:13 UTC, AksPokl commented on NumberOfDigitsInVariable.java
> +public class NumberOfDigitsInVariable {
Ты разве так выполнила? Нет
Я не вижу проверок на то, является ли число  однозначным, двухзначным или трехзначным

2019-10-12 17:13 UTC, AksPokl commented on AdditionalTask.java
> +        String[] endingWord = { "программист", "программиста", "программистов" };
Я оставила коммент возле массива - значит там)

2019-10-12 17:13 UTC, AksPokl commented on PositiveNumber.java
> +public class PositiveNumber {
Какой это таск?

2019-10-12 17:13 UTC, AksPokl commented on PositiveNumber.java
> +public class PositiveNumber {
Думаю 4 - Найти количество положительных чисел в исходном наборе.
Надо делать то, что просят в задании) Ты тут просто печатаешь - положительное число

2019-10-13 13:05 UTC, AksPokl requested changes

2019-10-13 13:05 UTC, AksPokl commented on AdditionalTask.java
> +        String[] endingWord = {"программист","программиста","программистов"};
{"программист", "программиста", "программистов"};
 Пробел нужно было убрать между {}
 а запятые должны разделяться пробелом)
Я во вторник покажу, как форматировать)

2019-10-13 13:05 UTC, AksPokl commented on PositiveNegativeApp.java
> +        if (number1 > 0) {
тут надо
if (число позитивное?)
else if(число отрицательное?)
else 10

2019-10-13 13:30 UTC, AksPokl approved these changes

2019-10-13 13:31 UTC, merged